<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250521210054 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE badge (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, awarded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, for_challenge_type VARCHAR(255) NOT NULL, challenge_profile_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_FEF0481DACEA0BB1 ON badge (challenge_profile_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE challenge_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(255) NOT NULL, sent_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, challenge_id INT DEFAULT NULL, profile_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_D707C01A98A21AC6 ON challenge_request (challenge_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_D707C01ACCFA12B8 ON challenge_request (profile_id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE badge ADD CONSTRAINT FK_FEF0481DACEA0BB1 FOREIGN KEY (challenge_profile_id) REFERENCES challenge_profile (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE challenge_request ADD CONSTRAINT FK_D707C01A98A21AC6 FOREIGN KEY (challenge_id) REFERENCES challenge (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE challenge_request ADD CONSTRAINT FK_D707C01ACCFA12B8 FOREIGN KEY (profile_id) REFERENCES "profile" (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE challenge ADD name VARCHAR(255) NOT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE challenge ADD status VARCHAR(255) NOT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE challenge ADD constraint_action VARCHAR(255) NOT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE challenge ADD constraint_content_type VARCHAR(255) NOT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE challenge ADD constraint_frequency VARCHAR(255) NOT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE challenge ADD constraint_target_count INT NOT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE challenge ADD creator_id INT DEFAULT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE challenge DROP description
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE challenge DROP created_at
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE challenge DROP updated_at
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE challenge ADD CONSTRAINT FK_D709895161220EA6 FOREIGN KEY (creator_id) REFERENCES "profile" (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_D709895161220EA6 ON challenge (creator_id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE challenge_profile ADD progress JSON NOT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE challenge_profile DROP role
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE challenge_profile DROP joined_at
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE challenge_profile DROP updated_at
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE challenge_profile DROP completed_at
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE challenge_profile ALTER challenge_id DROP NOT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE conversation ALTER archived_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE conversation ALTER archived_at SET NOT NULL
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            ALTER TABLE badge DROP CONSTRAINT FK_FEF0481DACEA0BB1
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE challenge_request DROP CONSTRAINT FK_D707C01A98A21AC6
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE challenge_request DROP CONSTRAINT FK_D707C01ACCFA12B8
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE badge
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE challenge_request
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE challenge_profile ADD role VARCHAR(255) NOT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE challenge_profile ADD joined_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE challenge_profile ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE challenge_profile ADD completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE challenge_profile DROP progress
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE challenge_profile ALTER challenge_id SET NOT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE challenge DROP CONSTRAINT FK_D709895161220EA6
        SQL);
        $this->addSql(<<<'SQL'
            DROP INDEX IDX_D709895161220EA6
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE challenge ADD description TEXT NOT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE challenge ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE challenge ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE challenge DROP name
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE challenge DROP status
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE challenge DROP constraint_action
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE challenge DROP constraint_content_type
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE challenge DROP constraint_frequency
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE challenge DROP constraint_target_count
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE challenge DROP creator_id
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE conversation ALTER archived_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE conversation ALTER archived_at DROP NOT NULL
        SQL);
    }
}
