<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250512181051 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE badge (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, for_challenge_type VARCHAR(255) NOT NULL, name VARCHAR(100) NOT NULL, image_path VARCHAR(255) DEFAULT NULL, config JSON DEFAULT NULL, showcase BOOLEAN DEFAULT false NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE challenge (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, action_type VARCHAR(255) NOT NULL, content_type VARCHAR(255) NOT NULL, quantity INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, challenge_type VARCHAR(255) NOT NULL, frequency VARCHAR(255) DEFAULT NULL, constraints JSON DEFAULT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE challenge_profile (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(255) NOT NULL, role VARCHAR(255) NOT NULL, joined_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, challenge_id INT NOT NULL, profile_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6DC7E58A98A21AC6 ON challenge_profile (challenge_id)');
        $this->addSql('CREATE INDEX IDX_6DC7E58ACCFA12B8 ON challenge_profile (profile_id)');
        $this->addSql('ALTER TABLE challenge_profile ADD CONSTRAINT FK_6DC7E58A98A21AC6 FOREIGN KEY (challenge_id) REFERENCES challenge (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE challenge_profile ADD CONSTRAINT FK_6DC7E58ACCFA12B8 FOREIGN KEY (profile_id) REFERENCES "profile" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE challenge_profile DROP CONSTRAINT FK_6DC7E58A98A21AC6');
        $this->addSql('ALTER TABLE challenge_profile DROP CONSTRAINT FK_6DC7E58ACCFA12B8');
        $this->addSql('DROP TABLE badge');
        $this->addSql('DROP TABLE challenge');
        $this->addSql('DROP TABLE challenge_profile');
    }
}
