<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250317095546 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE marks (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, target_id INT NOT NULL, target_type VARCHAR(50) NOT NULL, rating NUMERIC(3, 1) DEFAULT NULL, is_pinned BOOLEAN NOT NULL, is_favorite BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, profile_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_3C6AFA53CCFA12B8 ON marks (profile_id)');
        $this->addSql('ALTER TABLE marks ADD CONSTRAINT FK_3C6AFA53CCFA12B8 FOREIGN KEY (profile_id) REFERENCES "profile" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE marks DROP CONSTRAINT FK_3C6AFA53CCFA12B8');
        $this->addSql('DROP TABLE marks');
    }
}
