<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240904080303 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE chat_friendship (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, friend_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, requester_id INT NOT NULL, receiver_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B5C5E1F9ED442CF4 ON chat_friendship (requester_id)');
        $this->addSql('CREATE INDEX IDX_B5C5E1F9CD53EDB6 ON chat_friendship (receiver_id)');
        $this->addSql('ALTER TABLE chat_friendship ADD CONSTRAINT FK_B5C5E1F9ED442CF4 FOREIGN KEY (requester_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE chat_friendship ADD CONSTRAINT FK_B5C5E1F9CD53EDB6 FOREIGN KEY (receiver_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE friendship DROP CONSTRAINT fk_7234a45fed442cf4');
        $this->addSql('ALTER TABLE friendship DROP CONSTRAINT fk_7234a45fcd53edb6');
        $this->addSql('DROP TABLE friendship');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('CREATE TABLE friendship (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, friend_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, requester_id INT NOT NULL, receiver_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_7234a45fcd53edb6 ON friendship (receiver_id)');
        $this->addSql('CREATE INDEX idx_7234a45fed442cf4 ON friendship (requester_id)');
        $this->addSql('ALTER TABLE friendship ADD CONSTRAINT fk_7234a45fed442cf4 FOREIGN KEY (requester_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE friendship ADD CONSTRAINT fk_7234a45fcd53edb6 FOREIGN KEY (receiver_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE chat_friendship DROP CONSTRAINT FK_B5C5E1F9ED442CF4');
        $this->addSql('ALTER TABLE chat_friendship DROP CONSTRAINT FK_B5C5E1F9CD53EDB6');
        $this->addSql('DROP TABLE chat_friendship');
    }
}
